import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useSession } from 'next-auth/react'
import Navbar from '@component/components/Navbar'
// import Center from '../components/Center'
import { getProviders, signIn } from "next-auth/react";
import Image from "next/image";
import logocircle from '/public/Spotify_Icon_RGB_Black.png'
import Login from './login';
import Link from 'next/link'
// imports from center file
// import { ChevronDownIcon } from "@heroicons/react/outline"
import { useState, useEffect } from "react"
import { shuffle } from "lodash"
export default function Home() {

  // manually wrote css in the globals.css lables the classes below 
const colors = [
  "pink",
  "blue",
  "green",
  "red",
];
  const { data: session }= useSession()
  const [color, setColor] = useState(null); 
  const randomNumber = Math.floor(Math.random() * 4); // rng for the variable of colors
  useEffect(() => {
    setColor(colors[randomNumber]); //calls the variable colors and picks a random one out of the variable selection
  }, [])


  console.log(color)
  console.log({ session })
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

        <Navbar/>
         <div className={`${color}`} > hello test</div>{/* takes the classname and puts the variable that works above to put the random classname that you want for the colors of choice */}
      <main className={styles.main}>
        <h1 className={styles.title}>
        {session ? 
        <div className="flex-grow text-white">
        <section className={` flex items-end space bg-gradient-to-b to-black ${color} h-80 text-white padding-8 w-full`}>
          <h1>hello</h1>
        </section>
      </div>
         :
         <div className="loginpage">
      <Image src={logocircle} alt="Spotify logo" className="login_logo" />
      
      <Link
              href='/api/auth/signin'
              onClick={e => {
                e.preventDefault()
                // signIn('spotify')
                signIn('spotify')
              }}>             
                Sign In             
            </Link>
      </div>
         }
        </h1>
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const providers = await getProviders();

  return {
    props: {
      providers,
    }
  }
}